# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(0, 100, size = (2, 3, 5))
a

array([[[22, 97, 16,  0,  3],
        [ 4, 46, 37, 73, 28],
        [60, 89, 48, 20, 57]],

       [[68, 67,  9, 65, 33],
        [96, 39,  3, 36, 93],
        [91, 84, 85, 64, 79]]])

In [4]:
# Method 2
a = np.random.rand(2, 3, 5)
a

array([[[0.42253168, 0.88139112, 0.02232497, 0.39371485, 0.41702237],
        [0.89177954, 0.21822932, 0.23591188, 0.50952919, 0.1006083 ],
        [0.4868167 , 0.99355467, 0.38019321, 0.94212032, 0.87080117]],

       [[0.36860901, 0.42415696, 0.70310739, 0.74337681, 0.6895127 ],
        [0.88763115, 0.2565431 , 0.68202085, 0.86661844, 0.85803237],
        [0.13109992, 0.86177196, 0.34621776, 0.64948115, 0.16350388]]])

In [5]:
# Method 3
a = np.random.sample((2, 3, 5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.87973572 0.37106406 0.10176814 0.89695192 0.23479521]
  [0.15770891 0.38786598 0.89559283 0.43137559 0.32666925]
  [0.04464966 0.38412284 0.10777366 0.13067568 0.39943784]]

 [[0.74909923 0.1480736  0.28680112 0.6044225  0.67980595]
  [0.80999566 0.79146285 0.68533671 0.53400054 0.69154562]
  [0.65366722 0.50555675 0.03370688 0.61698553 0.24400155]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3), dtype = int)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

"""
If they don't have the same shape (as it is the case), it is possible, but first they 
must be broadcasted to a common shape (which becomes the shape of the output).

sources: 
--- https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html
--- https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

For instance, if we:
"""
try:
    print(np.add(a, b))
    
except ValueError:
    print("We get this message: 'ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)")

We get this message: 'ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
"""
went with reshape because we can think of it as a more powerful version of transpose. 
With transpose, the number of dimensions and the size of each one is fixed, it’s only the 
order than can change. With reshape, we can modify (almost) everything about the shape of the
array, including the number of dimensions.
"""

c = np.reshape(b, a.shape)

print(a.shape)
print(b.shape)
print(c.shape)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a, c)
print(d)

[[[1.87973572 1.37106406 1.10176814 1.89695192 1.23479521]
  [1.15770891 1.38786598 1.89559283 1.43137559 1.32666925]
  [1.04464966 1.38412284 1.10777366 1.13067568 1.39943784]]

 [[1.74909923 1.1480736  1.28680112 1.6044225  1.67980595]
  [1.80999566 1.79146285 1.68533671 1.53400054 1.69154562]
  [1.65366722 1.50555675 1.03370688 1.61698553 1.24400155]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print("a:\n", a)
print()
print("d:\n", d)

# because d is the sum of each element in a w/each element in c; since all the elements in
# c are one's, every element in d is element in a + 1.

a:
 [[[0.87973572 0.37106406 0.10176814 0.89695192 0.23479521]
  [0.15770891 0.38786598 0.89559283 0.43137559 0.32666925]
  [0.04464966 0.38412284 0.10777366 0.13067568 0.39943784]]

 [[0.74909923 0.1480736  0.28680112 0.6044225  0.67980595]
  [0.80999566 0.79146285 0.68533671 0.53400054 0.69154562]
  [0.65366722 0.50555675 0.03370688 0.61698553 0.24400155]]]

d:
 [[[1.87973572 1.37106406 1.10176814 1.89695192 1.23479521]
  [1.15770891 1.38786598 1.89559283 1.43137559 1.32666925]
  [1.04464966 1.38412284 1.10777366 1.13067568 1.39943784]]

 [[1.74909923 1.1480736  1.28680112 1.6044225  1.67980595]
  [1.80999566 1.79146285 1.68533671 1.53400054 1.69154562]
  [1.65366722 1.50555675 1.03370688 1.61698553 1.24400155]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a

# because a number multiplied by 1 is itself, and that's what's happening.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.8969519167350994 1.033706883970594 1.4594883010505986


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty(d.shape)
f.shape


(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
        
    if d_mean < x < d_max:
        f += [75]
        
    if x == d_mean:
        f += [50]
        
    if x == d_min:
        f += [0]
        
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d, f)

[[[1.87973572 1.37106406 1.10176814 1.89695192 1.23479521]
  [1.15770891 1.38786598 1.89559283 1.43137559 1.32666925]
  [1.04464966 1.38412284 1.10777366 1.13067568 1.39943784]]

 [[1.74909923 1.1480736  1.28680112 1.6044225  1.67980595]
  [1.80999566 1.79146285 1.68533671 1.53400054 1.69154562]
  [1.65366722 1.50555675 1.03370688 1.61698553 1.24400155]]] [[[ 75  25  25 100  25]
  [ 25  25  75  25  25]
  [ 25  25  25  25  25]]

 [[ 75  25  25  75  75]
  [ 75  75  75  75  75]
  [ 75  75   0  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here
j = list()
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
        
    if d_mean < x < d_max:
        j += ['D']
        
    if x == d_mean:
        j += ['C']
        
    if x == d_min:
        j += ['A']
        
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)

[[['D' 'B' 'B' 'E' 'B']
  ['B' 'B' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['D' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'A' 'D' 'B']]]
